// Generated by gencpp from file sensor_fusion_comm/InitHeightRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_FUSION_COMM_MESSAGE_INITHEIGHTREQUEST_H
#define SENSOR_FUSION_COMM_MESSAGE_INITHEIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_fusion_comm
{
template <class ContainerAllocator>
struct InitHeightRequest_
{
  typedef InitHeightRequest_<ContainerAllocator> Type;

  InitHeightRequest_()
    : height(0.0)  {
    }
  InitHeightRequest_(const ContainerAllocator& _alloc)
    : height(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitHeightRequest_

typedef ::sensor_fusion_comm::InitHeightRequest_<std::allocator<void> > InitHeightRequest;

typedef boost::shared_ptr< ::sensor_fusion_comm::InitHeightRequest > InitHeightRequestPtr;
typedef boost::shared_ptr< ::sensor_fusion_comm::InitHeightRequest const> InitHeightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator1> & lhs, const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator1> & lhs, const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_fusion_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "384d8dd5cbcb4f6e145e6b246fa635b2";
  }

  static const char* value(const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x384d8dd5cbcb4f6eULL;
  static const uint64_t static_value2 = 0x145e6b246fa635b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_fusion_comm/InitHeightRequest";
  }

  static const char* value(const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n"
;
  }

  static const char* value(const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitHeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_fusion_comm::InitHeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_FUSION_COMM_MESSAGE_INITHEIGHTREQUEST_H
